apiVersion: v1
kind: Pod
metadata:
  name: hostpath-pod
spec:
  containers:
  - image : nginx
    name : hostpath-pod
    volumeMounts:
    - mountPath: /test-pd
      name: test-volume
  volumes:
  - name: test-volume
    hostPath:
      path: /data
      type: Directory