apiVersion: v1
kind: Pod
metadata:
  name: env_test
spec:
  containers:
  - name: env_test
    image: wallowitch2/configmap_test
    ports:
    - containerPort: 80
    env:
    - name: Background-color
      valueFrom:
        secretKeyRef:
          name: color
          key: red
