apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  dbhost: 
  dbname: 
  dbuser: 
  dbpasswd: 


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: secrettest-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: secrettest
  template:
    metadata:
      labels:
        app: secrettest
    spec:
      containers:
      - name: secrettest
        image: wallowitch2/secrettest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: secrettest-service
spec:
  selector:
    app: secrettest
  ports:
  - protocol: TCP
    port: 80
    nodePort: 30080
  type: NodePort
